# 1. Database Connection Link (JDBC URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/makeitshort

# 2. Database Login Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# 3. Hibernate Lifecycle Rules
spring.jpa.hibernate.ddl-auto=update

# 4. Debugging Tool
spring.jpa.show-sql=true
